import os
import numpy as np
from gunpowder.caffe.net_io_wrapper import NetIoWrapper
from gunpowder.ext import caffe

class CaffePredict(object):
    '''Augments a batch with network predictions.

    Args:

        prototxt (string): Filename of the network prototxt.

        weights (string): Filename of the network weights.

        inputs (dict): Dictionary from the names of input layers in the
            network to :class:``VolumeType`` or batch attribute name as string.

        outputs (dict): Dictionary from the names of output layers in the
            network to :class:``VolumeType``. New volumes will be generated by
            this node for each entry (if requested downstream).

        gpu (int): Which GPU to use.
    '''

    def __init__(self,
                 prototxt,
                 weights,
                 input_key,
                 output_key,
                 gpu):

        # TODO validate that gpu is available
        assert os.path.exists(prototxt)
        assert os.path.exists(weights)
        for f in [prototxt, weights]:
            if not os.path.isfile(f):
                raise RuntimeError("%s does not exist" % f)
        self.prototxt = prototxt
        self.weights = weights
        self.input_key = input_key
        self.output_key = output_key

        caffe.enumerate_devices(False)
        caffe.set_devices((gpu,))
        caffe.set_mode_gpu()
        caffe.select_device(gpu, False)

        self.net = caffe.Net(self.prototxt, self.weights, caffe.TEST)
        self.net_io = NetIoWrapper(self.net, [self.output_key])

    def __call__(self, input_data):
        assert isinstance(input_data, np.ndarray)
        self.net_io.set_inputs({self.input_key: input_data})

        self.net.forward()
        output = self.net_io.get_outputs()[self.output_key]
        assert isinstance(output, np.ndarray)
        if output.ndim == 5:
            output = output[0]
        assert output.ndim == 4
        return output.astype('float32')
